image: php:7.2

insight:
    script:
        - curl -o insight.phar -s https://get.insight.symfony.com/insight.phar
        - php insight.phar analyze --no-interaction --no-ansi \
            <project-uuid> \
            --reference=$CI_COMMIT_SHA \
            --user-uuid=<your-user-uuid> \
            --api-token=<your-api-token> \
            --fail-condition="<fail-condition>"

