test:
    stage: test
    script:
        - cp .env.test .env
        # Install & enable Xdebug for code coverage reports
        - pecl install xdebug
        - docker-php-ext-enable xdebug
        - php bin/console doctrine:migrations:migrate -e test
        - php bin/console doctrine:fixture:load --no-interaction -e test
        - php composer.phar test-gitlab