pages:
  image: php:7.2
  script:
    - echo "Despliegue, sin operacion."
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php 
    - php -r "unlink('composer-setup.php');"
  # Si necesita, aqui se podra ejecutar comandos shell para instalar su
  # sitio web. En el caso de; website de CreaSoft.dev, instalamos eleventy. 

  artifacts:
    paths:
    - public

  only:
  - main