security-checker:
    stage: SecurityChecker
    script:
        - security-checker security:check composer.lock
        - local-php-security-checker  --path=./composer.lock
    allow_failure: false

phpcs:
        - php bin/console doctrine:migration:migrate --env=test --no-interaction
    script:
        - php bin/phpunit
    allow_failure: false
    allow_failure: false

