App\Entity\Viajes:
    properties:
          codigo_viaje:
              - NotBlank: 
                    message: "Error el campo codigo no puede quedar vacio"
          num_plaza:
              - NotBlank: 
                    message: "Error el campo numero plaza no puede quedar vacio"
          destino:      
              - NotBlank: 
                    message: "Error el campo Destino no puede quedar vacio"
          origen:
              - NotBlank: 
                    message: "Error el campo Lugar Origen no puede quedar vacio"
          precio:
              - NotBlank: 
                    message: "Error el campo codigo no puede quedar vacio"
App\Entity\Cliente:
    properties:
          name:
              - NotBlank: 
                    message: "Error el campo Nombre no puede quedar vacio"
          fecha_nacimiento:
              - NotBlank: 
                    message: "Error el campo nombre no puede quedar vacio"
          cedula:
              - NotBlank: 
                    message: "Error el campo Cedula no puede quedar vacio"
          telf:
              - NotBlank: 
                    message: "Error el campo Telefono no puede quedar vacio"